version: '3.8'
services:
  my_mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://my_mongodb:27017/pixLister
    depends_on:
      - my_mongodb

volumes:
  mongo-data:
